# SITE CONFIGURATION
title: MrRice Blog # your site title
#baseurl 直接注释调的话  在本地和线上都正常，但是如果打开  则会冲突，本地的/blog可以访问 但是到线上要  /
#relative_url: "/blog"
#baseurl: "/blog"
#url:  http://localhost:4000 #本地
#url: "https://mrrice996.github.io"
#url: "http://mrrice.top"

# SEO PLUGIN
#social:
#  name: Your Name
#  links:
#    - https://twitter.com/BenBalter
#    - https://www.facebook.com/ben.balter
#    - https://www.linkedin.com/in/BenBalter
#    - https://plus.google.com/+BenBalter
#    - https://github.com/benbalter
#    - https://keybase.io/benbalter

tagline: Code is as elegant as poetry
email: mailTo:mrrice1202@163.com
github: https://github.com/MrRice996
hero_img: posts/sleek_sm.jpg

# THEME SETTINGS
navigation: # Navigation links
  - { name: '主页', link: '/' }
  - { name: '标签', link: '/contents' }

#自定义标签 k:名字 v:图片路径
labels:
  - { k: 'Linux', v: '' }
  - { k: 'Record', v: '203933.jpg' }


# 分页
gems: [ jekyll-paginate ]
# 每页有几个项目
paginate: 12
paginate_path: "page:num"
pageName: page


# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

#Service Worker 的缓存技术  但是开启后有些报错，应该还没配置好
#service_worker: false

# BUILD SETTINGS
#markdown: kramdown
#highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem

#转换时排除某些文件、文件夹
exclude:
  - node_modules
  - script
  - package.json
  - vendor
  - npm-debug.log
  - gulpfile.js

#include: ['_pages']
#permalink: /:title/

#详情查看 compress.html
compress_html:
  clippings: all

plugins:
  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-seo-tag
